project_id = "hssrytzedacchvkrxgnq"

[functions.admin-ai-chat]
verify_jwt = true

[functions.generate-ai-suggestions]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-parent-notification]
verify_jwt = true
