project_id = "hssrytzedacchvkrxgnq"

[functions.admin-ai-chat]
verify_jwt = true

[functions.generate-ai-suggestions]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-parent-notification]
verify_jwt = true

[functions.send-arthur-notifications]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.send-parent-verification-email]
verify_jwt = true

[functions.send-data-export-email]
verify_jwt = true

[functions.send-data-deletion-email]
verify_jwt = true

[functions.guardian-start]
verify_jwt = true

[functions.guardian-verify]
verify_jwt = true

[functions.data-export-request]
verify_jwt = true

[functions.data-delete-request]
verify_jwt = true

[functions.data-delete-cancel]
verify_jwt = true

[functions.trivia-submit]
verify_jwt = true

[functions.trivia-notify-saturday]
verify_jwt = false

[functions.trivia-notify-sunday]
verify_jwt = false

[functions.trivia-generate-weekly-rounds]
verify_jwt = false

[functions.trivia-publish-rounds]
verify_jwt = false

[functions.local-help]
verify_jwt = false

[functions.create-product-stripe]
verify_jwt = true

[functions.create-product-checkout]
verify_jwt = true
